/**
 * 
 */
$(document).ready(function(){	
$("#loginbtn").click(function(){
		 $(".formlogin").addClass("was-validated");
		});$("#loginbtn").click(function(){
		 $(".formlogin").addClass("was-validated");
		});
});		